// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseData;

namespace WarehouseMigrations.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20210507104012_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WarehouseData.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpirationDate = new DateTime(2021, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            ExpirationDate = new DateTime(2021, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 9,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            ExpirationDate = new DateTime(2021, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            ExpirationDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("WarehouseData.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satay Chicken Nuddeln"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cannelloni al Formaggio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dumpling Soup"
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Salad Bowl"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lasagne con Pomodoro"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Spinach Salad"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Muesli with Raspberry"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Nut Butter Balls"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Popcorn with Raspberry"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Yogurt Parfait"
                        });
                });

            modelBuilder.Entity("WarehouseData.Models.Batch", b =>
                {
                    b.HasOne("WarehouseData.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
